name: mymoney
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  dio: ^4.0.6
  flutter_secure_storage: ^8.0.0
  gauge_indicator: ^0.4.3
  fl_chart: ^0.36.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  dio_http2_adapter: ^2.0.0

flutter:
  uses-material-design: true

  # Add your assets and fonts here
